### PR TITLE
fixing image bug by adding the default image to the item model on the…

### PR DESCRIPTION
**Pull request by HugoEsteves21**
… backend

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks HugoEsteves21, I'll review the changes right away!

**Review by ghost — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by ghost — APPROVED** [review]
Excellent job HugoEsteves21! You're now able to merge the PR.

**Comment by HugoEsteves21** [comment]
image

**Pull request merged**
